--- 
plugin: aws_ec2
regions:
  - us-east-1
filters:
  # this selects only running instances with tag Name of value Ansible
  "tag:Name": "Ansible"
  "instance-state-name": "running"
keyed_groups:
  - key: tags.Name
    prefix: 'tag_'
