apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306  # MySQL default port.
      name: mysql
  clusterIP: None  # This creates a headless service with no cluster IP.
  selector:
    app: mysql  # This matches Pods created by the StatefulSet using the label `app: mysql`.

